name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Create secret environment file
        run: |
          echo "export const environment = {
            production: true,
            firebaseConfig: {
              apiKey: '${{ secrets.FIREBASE_API_KEY }}',
              authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}',
              projectId: '${{ secrets.FIREBASE_PROJECT_ID }}',
              storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}',
              messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}',
              appId: '${{ secrets.FIREBASE_APP_ID }}',
              measurementId: '${{ secrets.FIREBASE_MEASUREMENT_ID }}'
            },
            cloudinary: {
              cloudName: '${{ secrets.CLOUDINARY_CLOUD_NAME }}',
              uploadPreset: '${{ secrets.CLOUDINARY_UPLOAD_PRESET }}'
            }
          };" > src/environments/environment.prod.secret.ts

      - name: Install dependencies
        run: npm install

      - name: Build for production
        run: npm run build -- --configuration production
