declare namespace NodeJS {
  interface ProcessEnv {
    NG_APP_CLOUDINARY_CLOUD_NAME: string;
    NG_APP_CLOUDINARY_UPLOAD_PRESET: string;
    NG_APP_FIREBASE_API_KEY: string;
    NG_APP_FIREBASE_APP_ID: string;
    NG_APP_FIREBASE_AUTH_DOMAIN: string;
    NG_APP_FIREBASE_MEASUREMENT_ID: string;
    NG_APP_FIREBASE_MESSAGING_SENDER_ID: string;
    NG_APP_FIREBASE_PROJECT_ID: string;
    NG_APP_FIREBASE_STORAGE_BUCKET: string;
    NG_APP_REMOVE_BG_API_KEY: string;
  }
}
